#######################################################
# 
# ActivityRecord.py
# Python implementation of the Class ActivityRecord
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:27:25 PM
# 
#######################################################
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.String import String
from CIM_STD_PYTHON.TC57CIM.IEC61968.Common.Status import Status
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class ActivityRecord(IdentifiedObject):
    """Records activity for an entity at a point in time; activity may be for an event
    that has already occurred or for a planned activity.
    """
    pass
