#######################################################
# 
# BoundaryFlow.py
# Python implementation of the Class BoundaryFlow
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 11:57:33 PM
# Original author: selaost1
# 
#######################################################
# from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from CIM_STD_PYTHON.TC57CIM.IEC61970.InfIEC61970.EnergyArea.EnergySchedulingAreaBoundary import EnergySchedulingAreaBoundary
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.Terminal import Terminal
from CIM_STD_PYTHON.TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

class BoundaryFlow(IdentifiedObject):
    m_EnergySchedulingAreaBoundary= EnergySchedulingAreaBoundary()

    m_Terminal= Terminal()
