#######################################################
# 
# RemoteUnitType.py
# Python implementation of the Class RemoteUnitType
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:19:26 PM
# 
#######################################################


class RemoteUnitType:
    """Type of remote unit.
    """
    def __init__(self):
        pass
