#######################################################
# 
# Source.py
# Python implementation of the Class Source
# Generated by Enterprise Architect
# Created on:      17-Dec-2023 7:19:42 PM
# 
#######################################################


class Source:
    """Source gives information related to the origin of a value.
    """
    pass
