
class GossCoreConstants:
    PROP_CORE_CONFIG = "pnnl.goss.core"
    PROP_CORE_CLIENT_CONFIG = "pnnl.goss.core.client"
    PROP_OPENWIRE_URI = "goss.openwire.uri"
    PROP_STOMP_URI = "goss.stomp.uri"
    PROP_SSL_ENABLED = "ssl.enabled"
    PROP_SSL_URI = "goss.ssl.uri"
    PROP_SSL_CLIENT_TRUSTSTORE = "client.truststore"
    PROP_SSL_CLIENT_TRUSTSTORE_PASSWORD = "client.truststore.password"
    PROP_SYSTEM_USER = "goss.system.user"
    PROP_SYSTEM_PASSWORD = "goss.system.password"
    PROP_LDAP_URI = "goss.ldap.uri"
    PROP_LDAP_ADMIN_USER = "goss.ldap.admin.user"
    PROP_LDAP_ADMIN_PASSWORD = "goss.ldap.admin.password"
    PROP_USE_AUTHORIZATION = "goss.use.authorization"
    PROP_DATASOURCES_CONFIG = "pnnl.goss.datasources"
    PROP_ACTIVEMQ_CONFIG = "pnnl.goss.activemq.config"
    PROP_REQUEST_QUEUE = "pnnl.goss.request.topic"
    PROP_TICK_TOPIC = "pnnl.goss.tick.topic"
    PROP_TOKEN_QUEUE = "pnnl.goss.token.topic"
