@startjson
{
  "AsynchronousMachine": {
    "IdentifiedObject": {
      "mRID": "123456",
      "name": "ASyncMachine1"
    },
    "type": [
      "GeneratingUnit",
      "RotatingMachine",
      "RegulatingCondEq"
    ],
    "AsynchronousMachine": {
      "ratedElectricalPower": "950",
      "ratedVoltage": "13800",
      "ratedMechanicalPower": "1000"
    },
    "Equipment": {
      "Location": "Substation1"
    }
  }
}
@endjson
