@startjson
{
  "BusbarSection": {
    "ConductingEquipment": {
      "BaseVoltage": "132000"
    },
    "Equipment": {
      "EquipmentContainer": "SomeContainerID"
    },
    "type": "ConductingEquipment"
  }
}
@endjson
