@startjson
{
  "EquipmentContainer1": {
    "type": 
      "EquipmentContainer"
    ,
    "EquipmentContainer": {
      "Equipment": 
        "Transformer1"
      ,
      "name": 
        "Container1"
      
    }
  },
  "Transformer1": {
    "IdentifiedObject": {
      "name": 
        "Transformer1"
      
    },
    "type": 
      "Transformer"
    
  },
  "Clamp1": {
    "Clamp": {
      "nominalDiameter": 
        "10.0"
      ,
      "nominalVoltage": 
        "110"
      ,
      "clampType": 
        "ABC123"
      ,
      "currentRating": 
        "100"
      ,
      "temperatureRating": 
        "90"
      
    },
    "Equipment": {
      "Equipment": 
        "EquipmentContainer1"
      
    },
    "type": 
      "Clamp"
    
  }
}
@endjson