@startjson
{
  "Conductor": {
    "comment": "An overhead electrical line conductor.",
    "subClassOf": [
      "Equipment",
      "ConductingEquipment"
    ],
    "type": "Class",
    "label": "Conductor"
  }
}
@endjson
