@startjson
{
  "EarthFaultCompensator": {
    "ShuntCompensator": {
      "nomU": "11000.0",
      "grounded": "0.0",
      "phaseConnection": "PhaseShuntConnectionKind.Yn",
      "sections": "1",
      "nomQ": "100.0"
    },
    "type": "LinearShuntCompensator"
  }
}
@endjson
