@startjson
{
  "EarthFaultCompensator_EFC1": {
    "EarthFaultCompensator": {
      "earthFault": 
        "EarthFault_EF1"
      ,
      "roundingFactor": 
        "0.1"
      
    },
    "IdentifiedObject": {
      "mRID": 
        "EFC1"
      ,
      "name": 
        "EarthFaultCompensator 1"
      
    },
    "RegulatingCondEq": {
      "RegulatingControl": 
        "RegulatingControl_RC1"
      ,
      "operatingMode": 
        "enabled"
      
    },
    "type": 
      "EarthFaultCompensator"
    
  }
}
@endjson