@startjson
{
  "EnergyConsumer": {
    "type": "EnergyConsumer",
    "IdentifiedObject": {
      "name": "EnergyConsumer1",
      "mRID": "EC1"
    },
    "PowerSystemResource": {
      "nominalVoltage": "11000.0"
    }
  }
}
@endjson
