@startjson
{
  "fuse_001": {
    "Equipment": {
      "EquipmentContainer": "substation1"
    },
    "Fuse": {
      "operatingTime": "200.0",
      "ratedVoltage": "110.0",
      "ratedCurrent": "100.0"
    },
    "type": "Fuse",
    "IdentifiedObject": {
      "mRID": "FUSE_001",
      "name": "Fuse 1"
    },
    "PowerSystemResource": {
      "AssetPSRType": "AssetPSRType._fuse"
    }
  }
}
@endjson
