@startjson
{
  "LinearShuntCompensator": {
    "ShuntCompensator": {
      "delay0": "0.0",
      "nomQ": "100.0",
      "aVRToManualModeTime": "0.0",
      "linElems": "PowerTransformerEnd1",
      "aVRDelay": "timeDelay",
      "stepVoltageIncrement": "200.0",
      "normalSections": "8",
      "bPerSection": "20.0",
      "nomU": "11000.0",
      "minimumReactivePower": "-500.0",
      "maximumReactivePower": "500.0",
      "maximumSections": "10",
      "gPerSection": "0.0",
      "bAVR": "0.0"
    },
    "type": "ShuntCompensator",
    "RegulatingCondEq": {
      "regulationCapability": "true"
    },
    "IdentifiedObject": {
      "name": "LSCompensator1"
    }
  },
  "timeDelay": {
    "UnitMultiplier": "0.001",
    "label": "Time Delay",
    "UnitSymbol": "ms",
    "type": "Seconds"
  }
}
@endjson
