@startjson
{
  "LoadBreakSwitch": {
    "Switch": {
      "normalOpen": "false",
      "ratedVoltage": "110.0",
      "ratedCurrent": "1200.0"
    },
    "ProtectedSwitch": {
      "normalOpen": "false"
    },
    "type": [
      "SwitchingDevice",
      "ConductingEquipment",
      "ProtectedSwitch",
      "Switch"
    ],
    "IdentifiedObject": {
      "mRID": "123456",
      "name": "LoadBreakSwitch1"
    },
    "Equipment": {
      "EquipmentContainer": "Substation1"
    }
  }
}
@endjson
