@startjson
{
  "ratedSValue": {
    "unit": "VA",
    "multiplier": "M",
    "value": "100",
    "type": "ApparentPower"
  },
  "powerTransformer1": {
    "operatingMode": "HV",
    "type": "PowerTransformer",
    "ratedS": "ratedSValue"
  },
  "PhaseTapChangerSymmetrical": {
    "neutralStep": "neutralStepValue",
    "nomU": "nomUValue",
    "type": "PhaseTapChangerSymmetrical",
    "PowerTransformer": "powerTransformer1",
    "step": "stepValue"
  },
  "nomUValue": {
    "type": "Voltage",
    "multiplier": "k",
    "unit": "V",
    "value": "110"
  },
  "stepValue": {
    "type": "Integer",
    "value": "3"
  },
  "neutralStepValue": {
    "type": "Integer",
    "value": "1"
  }
}
@endjson
