@startjson
{
  "PowerTransformer": {
    "IdentifiedObject": {
      "name": "ExamplePowerTransformer",
      "description": "This is an example of a power transformer"
    },
    "PowerTransformer": {
      "vectorGroup": "Dyn11",
      "PowerTransformerEnd": [
        "PTEnd1",
        "PTEnd2"
      ]
    },
    "PowerSystemResource": {
      "AssetDatasheet": "ExampleDatasheet123"
    },
    "type": "PowerTransformer",
    "Equipment": {
      "EquipmentContainer": "Substation123"
    }
  },
  "PTEnd1": {
    "PowerSystemResource": {
      "AssetDatasheet": "End1Datasheet456"
    },
    "TransformerEnd": {
      "ratedU": "132.0",
      "ratedInsulationLevel": "123.0",
      "ratedS": "10.0"
    },
    "type": "PowerTransformerEnd"
  },
  "PTEnd2": {
    "TransformerEnd": {
      "ratedInsulationLevel": "123.0",
      "ratedS": "10.0",
      "ratedU": "33.0"
    },
    "type": "PowerTransformerEnd",
    "PowerSystemResource": {
      "AssetDatasheet": "End2Datasheet789"
    }
  },
  "Substation123": {
    "IdentifiedObject": {
      "name": "ExampleSubstation",
      "description": "This is an example substation"
    },
    "type": "Substation"
  }
}
@endjson
