@startjson
{
  "RegulatingControl": {
    "RegulatingControl": {
      "targetValue": "1.0",
      "targetDeadband": "0.01",
      "RegulatingControlType": "voltage",
      "enabled": "true",
      "discrete": "false"
    },
    "type": "RegulatingControl"
  }
}
@endjson
