@startjson
{
  "SinglePhaseKind": {
    "type": "Class",
    "comment": "The type of single phase connection.",
    "label": "SinglePhaseKind",
    "symbol": "SinglePhaseKind",
    "subClassOf": "SinglePhaseType"
  }
}
@endjson
