@startjson
{
  "VoltageControlMode": {
    "subClassOf": "SVCControlMode",
    "type": "Class",
    "comment": "A voltage control mode"
  },
  "SVCControlMode": {
    "comment": "A voltage control mode employed by a static var compensator (SVC)",
    "subClassOf": "ControlMode",
    "type": "Class"
  }
}
@endjson
