@startjson
{
  "SwitchingAction_1": {
    "IdentifiedObject": {
      "description": "Ensure safety before maintenance",
      "mRID": "SwitchingAction_1",
      "name": "Switching Action 1"
    },
    "SwitchingAction": {
      "scheduled": "2023-01-01T08:00:00",
      "Switch": "LoadBreakSwitch_1"
    },
    "type": "SwitchingAction"
  },
  "SwitchSchedule_1": {
    "Schedule": {
      "startTime": "2023-01-01T08:00:00",
      "endTime": "2023-01-01T16:00:00"
    },
    "type": "SwitchSchedule",
    "IdentifiedObject": {
      "description": "Switching schedule for maintenance",
      "mRID": "SwitchSchedule_1",
      "name": "Schedule 1"
    },
    "SwitchSchedule": {
      "SwitchingAction": "SwitchingAction_1"
    }
  },
  "LoadBreakSwitch_1": {
    "IdentifiedObject": {
      "name": "Switch 1",
      "description": "Main distribution point switch",
      "mRID": "LoadBreakSwitch_1"
    },
    "type": "LoadBreakSwitch"
  }
}
@endjson
