@startjson
{
  "TapChangerControl1": {
    "type": [
      "TapChangerControl"
    ],
    "RegulatingControl": {
      "mode": [
        "voltage"
      ],
      "targetRange": [
        "VoltageLevel1"
      ]
    },
    "Equipment": {
      "EquipmentContainer": [
        "Substation1"
      ]
    },
    "IdentifiedObject": {
      "name": [
        "TapChangerControl1"
      ]
    }
  },
  "VoltageLevel1": {
    "IdentifiedObject": {
      "name": [
        "VoltageLevel1"
      ]
    },
    "type": [
      "VoltageLevel"
    ]
  },
  "Substation1": {
    "IdentifiedObject": {
      "name": [
        "Substation1"
      ]
    },
    "type": [
      "Substation"
    ]
  }
}
@endjson